GET http://localhost:3333/products

###
POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "Produto 1",
  "description": "Descrição do produto 1",
  "image_url": "https://player.vimeo.com/video/918456480",
  "price": 100
}
{
  "name": "Produto 2",
  "description": "Descrição do produto 1",
  "image_url": "https://player.vimeo.com/video/918456480",
  "price": 100
}